Task/apps 2655 fix chronicle server downloads
openlattice/chronicle-server pull request #160
Opened 2021-01-16 21:02 UTC by anzioka

implement Iterable interface

2021-01-20 23:02 UTC, makosblade requested changes
I like the general structure of this, using a supplier, iterator and iterable but it should definitely be written in Kotlin. There's no reason that we should be adding files written in Java anywhere in the codebase.

2021-01-21 02:52 UTC, anzioka commented on src/main/java/com/openlattice/chronicle/services/download/ParticipantDataIterable.java
> +package com.openlattice.chronicle.services.download;
done!

2021-01-21 22:50 UTC, geekbeast requested changes
Looks good, a requested change (synchronization) and some minor suggestions.

2021-01-21 22:50 UTC, geekbeast commented on src/main/java/com/openlattice/chronicle/services/download/ParticipantDataIterable.kt
> +                            val title = OutputConstants.APP_PREFIX + neighborPageSupplier.srcMetadata[propertyType.id]
title is nullable here. If it shouldn't be nullable use .getValue(...) instead [] index operator which will thrown an NPE if the property type id is not present.

2021-01-21 22:50 UTC, geekbeast commented on src/main/java/com/openlattice/chronicle/services/download/ParticipantDataIterable.kt
> +                                    ?.title
ditto.

2021-01-21 22:50 UTC, geekbeast commented on src/main/java/com/openlattice/chronicle/services/download/ParticipantDataIterable.kt
> +            lock.lock()
I don't understand the purpose of this lock. It isn't used outside of this function and seems to serve a synchronization mechanism for the method. Use ```@Synchronized``` annotation instead.

2021-01-22 01:58 UTC, makosblade approved these changes

2021-01-22 02:04 UTC, katherinebernstein approved these changes
This is awesome!! I left a few tiny comments on how to kotlinify some things, and one bigger suggestion about structuring things in a more readable way, but this looks great and none of those things should be blocking for getting this fix in! (Mostly intended as suggestions for updates/refactors for the future)

2021-01-23 01:06 UTC, geekbeast approved these changes

2021-01-23 01:06 UTC, merged