chronicle super user delete legacy data
openlattice/chronicle-server pull request #179
Opened 2021-06-08 23:45 UTC by anzioka

PR:
-> Regular CAFE users who own studies do not have OWNER on required edge entity sets, therefore are unable to delete participant data / studies. The workaround is to delegate deletion to chronicle super user

2021-06-14 23:29 UTC, UnsungHero97 requested changes

2021-06-14 23:29 UTC, UnsungHero97 commented on src/main/java/com/openlattice/chronicle/services/delete/DataDeletionService.java
> +                .getLegacyChronicleAppConfig( getParticipantEntitySetName( studyId ) );
What about non-legacy?

2021-06-14 23:29 UTC, UnsungHero97 commented on src/main/java/com/openlattice/chronicle/services/delete/DataDeletionService.java
> +            throw new ForbiddenException( "insufficient permission to delete data from participant entity set" );
`ensureOwnerAccess` does not know who the caller is so it does not know that the caller is trying to do a delete. Please update the error messages accordingly or rename the function to something like `ensureUserCanDeleteStudy`.

2021-06-15 23:30 UTC, UnsungHero97 requested changes

2021-06-15 23:30 UTC, UnsungHero97 commented on src/main/java/com/openlattice/chronicle/data/ChronicleSurveysAppConfig.java
> + * <p>
I believe you need a closing `</p>`.

2021-06-15 23:30 UTC, UnsungHero97 commented on src/main/java/com/openlattice/chronicle/services/delete/DataDeletionService.java
> +                permissionsApi.getAcl( aclKey );
Use `permissionsApi.getAcls` to make one request instead of multiple.

2021-06-16 23:47 UTC, UnsungHero97 approved these changes

2021-06-16 23:47 UTC, UnsungHero97 commented on src/main/java/com/openlattice/chronicle/services/delete/DataDeletionService.java
> +            chronicleDataApi.deleteEntities( participantsESID, participantsToDelete, deleteType, false );
No change required. `chronicleDataApi` and `userDataApi` are confusing. It should be either prod or integration.

2021-06-16 23:59 UTC, geekbeast approved these changes

2021-06-17 00:00 UTC, merged